// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/images": {
    params: {};
  };
  "/imageList": {
    params: {};
  };
  "/newImage": {
    params: {};
  };
  "/editImage": {
    params: {};
  };
  "/favoriteList": {
    params: {};
  };
  "/newFavorite": {
    params: {};
  };
  "/editFavorite": {
    params: {};
  };
  "/presentFavorite": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/images" | "/imageList" | "/newImage" | "/editImage" | "/favoriteList" | "/newFavorite" | "/editFavorite" | "/presentFavorite" | "/*";
  };
  "./components/MainLayout/MainLayout.tsx": {
    id: "components/MainLayout/MainLayout";
    page: "/" | "/about" | "/images" | "/imageList" | "/newImage" | "/editImage" | "/favoriteList" | "/newFavorite" | "/editFavorite" | "/presentFavorite" | "/*";
  };
  "./pages/About.tsx": {
    id: "pages/About";
    page: "/about";
  };
  "./pages/GetImages.tsx": {
    id: "pages/GetImages";
    page: "/images";
  };
  "./pages/Images.tsx": {
    id: "pages/Images";
    page: "/imageList";
  };
  "./pages/NewImage.tsx": {
    id: "pages/NewImage";
    page: "/newImage";
  };
  "./pages/EditImage.tsx": {
    id: "pages/EditImage";
    page: "/editImage";
  };
  "./pages/Favorites.tsx": {
    id: "pages/Favorites";
    page: "/favoriteList";
  };
  "./pages/NewFavorite.tsx": {
    id: "pages/NewFavorite";
    page: "/newFavorite";
  };
  "./pages/EditFavorite.tsx": {
    id: "pages/EditFavorite";
    page: "/editFavorite";
  };
  "./pages/PresentFavorite.tsx": {
    id: "pages/PresentFavorite";
    page: "/presentFavorite";
  };
  "./catchall.tsx": {
    id: "catchall";
    page: "/" | "/*";
  };
};